# Generated by Django 4.1.3 on 2022-11-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swimport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="guildMemberLevel",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
