# Generated by Django 4.1.3 on 2022-11-24 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("swimport", "0002_alter_player_guildmemberlevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="toon",
            name="xp",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Mod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modId", models.CharField(max_length=30)),
                ("modLevel", models.SmallIntegerField()),
                ("tier", models.SmallIntegerField()),
                ("set", models.SmallIntegerField()),
                ("pips", models.SmallIntegerField()),
                ("primaryStatType", models.CharField(max_length=30)),
                (
                    "primaryStatValue",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("secondaryStat1Type", models.CharField(max_length=30)),
                (
                    "secondaryStat1Value",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("secondaryStat1Roll", models.SmallIntegerField()),
                ("secondaryStat2Type", models.CharField(max_length=30)),
                (
                    "secondaryStat2Value",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("secondaryStat2Roll", models.SmallIntegerField()),
                ("secondaryStat3Type", models.CharField(max_length=30)),
                (
                    "secondaryStat3Value",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("secondaryStat3Roll", models.SmallIntegerField()),
                ("secondaryStat4Type", models.CharField(max_length=30)),
                (
                    "secondaryStat4Value",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("secondaryStat4Roll", models.SmallIntegerField()),
                (
                    "toon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="swimport.toon"
                    ),
                ),
            ],
        ),
    ]
