# Generated by Django 4.1.3 on 2022-11-24 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("swimport", "0003_toon_xp_mod"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skillId", models.CharField(max_length=30)),
                ("tier", models.SmallIntegerField()),
                ("nameKey", models.CharField(max_length=30)),
                ("isZeta", models.BooleanField()),
                ("tiers", models.SmallIntegerField()),
                (
                    "toon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="swimport.toon"
                    ),
                ),
            ],
        ),
    ]
