# Generated by Django 4.1.3 on 2022-11-24 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("swimport", "0004_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="isZeta",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Equipped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gear0Id", models.CharField(blank=True, max_length=6)),
                ("gear0Slot", models.SmallIntegerField(blank=True)),
                ("gear0NameKey", models.CharField(blank=True, max_length=35)),
                ("gear1Id", models.CharField(blank=True, max_length=6)),
                ("gear1Slot", models.SmallIntegerField(blank=True)),
                ("gear1NameKey", models.CharField(blank=True, max_length=35)),
                ("gear2Id", models.CharField(blank=True, max_length=6)),
                ("gear2Slot", models.SmallIntegerField(blank=True)),
                ("gear2NameKey", models.CharField(blank=True, max_length=35)),
                ("gear3Id", models.CharField(blank=True, max_length=6)),
                ("gear3Slot", models.SmallIntegerField(blank=True)),
                ("gear3NameKey", models.CharField(blank=True, max_length=35)),
                ("gear4Id", models.CharField(blank=True, max_length=6)),
                ("gear4Slot", models.SmallIntegerField(blank=True)),
                ("gear4NameKey", models.CharField(blank=True, max_length=35)),
                ("gear5Id", models.CharField(blank=True, max_length=6)),
                ("gear5Slot", models.SmallIntegerField(blank=True)),
                ("gear5NameKey", models.CharField(blank=True, max_length=35)),
                (
                    "toon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="swimport.toon"
                    ),
                ),
            ],
        ),
    ]
