# Generated by Django 4.1.3 on 2022-11-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swimport", "0005_alter_skill_iszeta_equipped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toon",
            name="combatType",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
