# Generated by Django 4.1.3 on 2022-11-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("swimport", "0006_alter_toon_combattype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mod",
            old_name="primaryStatType",
            new_name="priStatType",
        ),
        migrations.RenameField(
            model_name="mod",
            old_name="primaryStatValue",
            new_name="priStatValue",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="secondaryStat1Roll",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="secondaryStat1Type",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="secondaryStat1Value",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="secondaryStat2Roll",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="secondaryStat2Type",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="secondaryStat2Value",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="secondaryStat3Roll",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="secondaryStat3Type",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="secondaryStat3Value",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="secondaryStat4Roll",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="secondaryStat4Type",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="secondaryStat4Value",
        ),
        migrations.CreateModel(
            name="ModStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secStatType", models.CharField(max_length=30)),
                ("secStatValue", models.DecimalField(decimal_places=5, max_digits=10)),
                ("secStatRoll", models.SmallIntegerField()),
                (
                    "mod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="swimport.mod"
                    ),
                ),
            ],
        ),
    ]
