# Generated by Django 4.1.3 on 2022-11-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("swimport", "0008_rename_secstattype_modstat_stattype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipped",
            old_name="gear0Id",
            new_name="equipmentId",
        ),
        migrations.RenameField(
            model_name="equipped",
            old_name="gear0NameKey",
            new_name="nameKey",
        ),
        migrations.RenameField(
            model_name="equipped",
            old_name="gear0Slot",
            new_name="slot",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear1Id",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear1NameKey",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear1Slot",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear2Id",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear2NameKey",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear2Slot",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear3Id",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear3NameKey",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear3Slot",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear4Id",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear4NameKey",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear4Slot",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear5Id",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear5NameKey",
        ),
        migrations.RemoveField(
            model_name="equipped",
            name="gear5Slot",
        ),
    ]
