# Generated by Django 4.1.3 on 2022-11-26 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("swimport", "0009_rename_gear0id_equipped_equipmentid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mod",
            name="priStatType",
        ),
        migrations.RemoveField(
            model_name="mod",
            name="priStatValue",
        ),
    ]
