# Generated by Django 4.1.3 on 2022-11-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("swimport", "0010_remove_mod_pristattype_remove_mod_pristatvalue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modstat",
            old_name="StatRoll",
            new_name="statRoll",
        ),
        migrations.RenameField(
            model_name="modstat",
            old_name="StatType",
            new_name="statType",
        ),
        migrations.RenameField(
            model_name="modstat",
            old_name="StatValue",
            new_name="statValue",
        ),
    ]
